# Generated by Django 3.2.13 on 2022-11-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221103_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='캡처.jpg', upload_to='images/'),
        ),
    ]
