# Generated by Django 3.2.13 on 2022-11-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_followings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='캡처.jpg', upload_to=''),
        ),
    ]
